spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doro_load?serverTimezone=UTC&characterEncoding=UTF-8
    username: doro
    password: doro_pw
  data:
    redis:
      host: localhost
      port: 6379

doro:
  cors:
    allowed-origins:
      - http://localhost:5173

springdoc:
  swagger-ui:
    enabled: true
